SisRAEE/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^diagrams/', include('diagrams.urls')),
    url(r'^processes/', include('processes.urls')),
    #url(r'^chaining/', include('smart_selects.urls')),
]

diagrams/urls.py
from django.conf.urls import url
#from . import views
from diagrams.views import generateSankey,resultProcess

app_name = 'diagrams'
urlpatterns = [
    #url(r'^$', views.home),
    url(r'^$', resultProcess, name='diagramassankey'),
    url(r'^SankeyDiagrams', generateSankey,name='generateSankey'),
]

diagrams/models.py
from django.db import models

# Create your models here.

diagrams/views.py
from django.http import HttpResponse
from django.shortcuts import render

from DataBase.DataBaseQuery import getNombresMaterialesEquipoNombre, getTodosProcesos
from diagrams.analyzeDiagram import *

listaTotal=[]

global materiales
nombresProcesos=["XRF_Brominate","XRF_Phosphorous","XRT_FR","LIBS","Densities_1,03_upper","Densities_1,09_lower","Densities_1,15_upper","Densities_1,55_lower","Densities_1,095_upper","Densities_1,145_lower","Densities_1,185_lower"]

def resultProcess(request,best_profit,optimal_npv,optimal_intermediate_outputs,nombreEquipo,anioInicial, anioFinal):
    global nombresProcesos,materiales
    request.session['matrizprocesos'] = optimal_intermediate_outputs
    nombresProcesos = getTodosProcesos()
    materiales= getNombresMaterialesEquipoNombre(nombreEquipo)
    inversion = best_profit#vectorInvestment(best_profit)
    resultado=sequenceProcess(optimal_intermediate_outputs,anioInicial, anioFinal)
    resultadoNombre=nombresListaProcesos(resultado,nombresProcesos,inversion,optimal_npv,anioInicial, anioFinal)


    args = {
        'resultadoTotal': resultadoNombre,'equipo':nombreEquipo,'anio':anioInicial
    }
    return render(request, 'diagrams/diagramassankey.html',args)

def generateSankey(request):

    colorNodo = []
    anioCalculo=0
    procesos=''
    labelNodo = []
    source = []
    values = []
    target = []
    colorLink = []
    labelLink = []
    listaTotal=request.session['matrizprocesos']
    nombresProcesos = getTodosProcesos()
    materiales = ["ABS", "HIPS", "PC/ABS PFr", "HIPPS/PPE PFr", "ABS/PMMA", "HIPS BFr", "ABS BFr"]

    idProcess=0
    if request.method == 'POST':
        if str(request.POST.get('diagramsID')) != 'None':
            idProcess = int(request.POST.get('diagramsID'))
            referencia = int(request.POST.get('referencia'))
            procesos = (request.POST.get('procesos'))
            equipo=(request.POST.get('equipo'))
            aux=procesos.split("'")
            procesos=''
            for proc in aux:
                if proc!=']' and proc!='[' and proc!=', ':
                    if procesos!='':
                        procesos=procesos+' -> '+proc
                    else:
                        procesos = proc
            anio = int(request.POST.get('anio'))
            anioCalculo=anio+referencia
            lista = listaTotal[idProcess-1]
            listaPara=[]
            listaPara.append(lista[referencia])
            colorNodo, labelNodo, source, values, target, colorLink, labelLink = parametrosSankey(materiales, listaPara, 0)

    args = {
        'colorNodo': colorNodo, 'labelNodo': labelNodo, 'source': source, 'values': values, 'target': target,
        'colorLink': colorLink, 'labelLink': labelLink, 'anio': anioCalculo,'idProcesos':idProcess,'procesos':procesos,
        'equipo':equipo
    }
    print(colorNodo)
    print(labelNodo)
    print(source)
    print(values)
    print(target)
    print(colorLink)
    print(labelLink)
    print(idProcess)

    return render(request,'diagrams/sankey.html',args)

def vectorInvestment(vector):

    #vector=[[-90000.0, 12927.755724547314, 67500.0], [0, -98529.6, 0], [-145000.0, -102921.73633843375, 124285.71428571429], [-145000.0, -110454.06765852516, 124285.71428571429], [-145000.0, -110718.69836082301, 124285.71428571429], [-580000.0, -9502.951137066935, 497142.85714285716], [-580000.0, -10079.90618964308, 497142.85714285716], [-580000.0, -10198.585337120574, 497142.85714285716], [-580000.0, -10548.4287093514, 497142.85714285716], [-580000.0, -10951.403081891476, 497142.85714285716], [-580000.0, -12133.703141704958, 497142.85714285716]]
    #vector =[[-90000.0, 15779.71286716318, 67500.0], [0, -16529.702994445062, 0],
     #[-145000.0, -13224.079110827646, 124285.71428571429], [-145000.0, -13354.336909442776, 124285.71428571429],
     ##[-145000.0, -20100.11884124519, 124285.71428571429], [-225000.0, -31670.910937356733, 192857.14285714287],
     #[-290000.0, -16662.878288889013, 248571.42857142858], [-290000.0, -16790.53093153183, 248571.42857142858],
     #[-290000.0, -16794.494957627787, 248571.42857142858], [-290000.0, -16924.752756242902, 248571.42857142858],
     #[-290000.0, -16932.015752236126, 248571.42857142858]]
    vectorInversion=[]
    for list in vector:
        if list !=0:
            vectorInversion.append(list[0]*(-1))

    return vectorInversion

def reporteTablaDiagrama(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="ResultadoDiagrama.pdf"'

diagrams/templates/diagrams/Ejemplo.html
<svg id="sankey_svg" height="600" width="600" xmlns="http://www.w3.org/2000/svg" version="1.1"><title>Your Diagram
    Title</title><!-- Generated with SankeyMATIC on Tue Dec 04 2018 12:18:53 GMT-0500 (-05)-->
    <g>
        <rect width="100%" height="100%" fill="rgb(255, 255, 255)"></rect>
        <g transform="translate(12,12)">
            <g>
                <path class="link"
                      d="M10,276.39768098891125C146.5,276.39768098891125 146.5,276.5324708660649 283,276.5324708660649"
                      style="fill: none; stroke-width: 480; stroke: rgb(107, 174, 214); stroke-opacity: 0.4;"><title>
                    Wages &#8594; Budget:
                    2,000</title></path>
                <path class="link"
                      d="M293,96.53247086606487C429.5,96.53247086606487 429.5,60.00000000000009 566,60.00000000000009"
                      style="fill: none; stroke-width: 120; stroke: rgb(198, 219, 239); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Taxes:
                    500</title></path>
                <path class="link"
                      d="M293,210.53247086606487C429.5,210.53247086606487 429.5,192.00000000000009 566,192.00000000000009"
                      style="fill: none; stroke-width: 108; stroke: rgb(230, 85, 13); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Housing:
                    450</title></path>
                <path class="link"
                      d="M293,436.13247086606486C429.5,436.13247086606486 429.5,471.6000000000001 566,471.6000000000001"
                      style="fill: none; stroke-width: 96; stroke: rgb(253, 208, 162); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Health Care:
                    400</title></path>
                <path class="link"
                      d="M293,301.7324708660649C429.5,301.7324708660649 429.5,301.2000000000001 566,301.2000000000001"
                      style="fill: none; stroke-width: 74.4; stroke: rgb(253, 141, 60); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Food:
                    310</title></path>
                <path class="link"
                      d="M293,363.5324708660649C429.5,363.5324708660649 429.5,381.0000000000001 566,381.0000000000001"
                      style="fill: none; stroke-width: 49.2; stroke: rgb(253, 174, 107); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Transportation:
                    205</title></path>
                <path class="link"
                      d="M293,503.33247086606485C429.5,503.33247086606485 429.5,556.8000000000001 566,556.8000000000001"
                      style="fill: none; stroke-width: 38.4; stroke: rgb(49, 163, 84); stroke-opacity: 0.4;"><title>
                    Budget &#8594; Other Necessities:
                    160</title></path>
                <path class="link"
                      d="M10,537.3976809889112C146.5,537.3976809889112 146.5,519.5324708660648 283,519.5324708660648"
                      style="fill: none; stroke-width: 6; stroke: rgb(107, 174, 214); stroke-opacity: 0.4;"><title>
                    Interest &#8594; Budget:
                    25</title></path>
            </g>
            <g>
                <g class="node" transform="translate(0,36.39768098891125)">
                    <rect height="480" width="10" id="r0" shape-rendering="crispEdges"
                          style="fill: rgb(49, 130, 189); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(24, 63, 92);">
                        <title>Wages:
                            2,000</title></rect>
                    <text x="16" y="240" dy=".35em" text-anchor="start"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Wages: 2,000
                    </text>
                </g>
                <g class="node" transform="translate(283,36.53247086606488)">
                    <rect height="486" width="10" id="r1" shape-rendering="crispEdges"
                          style="fill: rgb(107, 174, 214); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(52, 85, 104);">
                        <title>Budget:
                            2,025</title></rect>
                    <text x="-6" y="243" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Budget: 2,025
                    </text>
                </g>
                <g class="node" transform="translate(0,534.3976809889112)">
                    <rect height="6" width="10" id="r2" shape-rendering="crispEdges"
                          style="fill: rgb(158, 202, 225); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(77, 98, 110);">
                        <title>Interest:
                            25</title></rect>
                    <text x="16" y="3" dy=".35em" text-anchor="start"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Interest: 25
                    </text>
                </g>
                <g class="node" transform="translate(566,9.237055564881302e-14)">
                    <rect height="120" width="10" id="r3" shape-rendering="crispEdges"
                          style="fill: rgb(198, 219, 239); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(97, 107, 117);">
                        <title>Taxes:
                            500</title></rect>
                    <text x="-6" y="60" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Taxes: 500
                    </text>
                </g>
                <g class="node" transform="translate(566,138.00000000000009)">
                    <rect height="108" width="10" id="r4" shape-rendering="crispEdges"
                          style="fill: rgb(230, 85, 13); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(112, 41, 6);">
                        <title>Housing:
                            450</title></rect>
                    <text x="-6" y="54" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Housing: 450
                    </text>
                </g>
                <g class="node" transform="translate(566,264.0000000000001)">
                    <rect height="74.39999999999999" width="10" id="r5" shape-rendering="crispEdges"
                          style="fill: rgb(253, 141, 60); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(123, 69, 29);">
                        <title>Food:
                            310</title></rect>
                    <text x="-6" y="37.199999999999996" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Food: 310
                    </text>
                </g>
                <g class="node" transform="translate(566,356.4000000000001)">
                    <rect height="49.199999999999996" width="10" id="r6" shape-rendering="crispEdges"
                          style="fill: rgb(253, 174, 107); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(123, 85, 52);">
                        <title>Transportation:
                            205</title></rect>
                    <text x="-6" y="24.599999999999998" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Transportation: 205
                    </text>
                </g>
                <g class="node" transform="translate(566,423.6000000000001)">
                    <rect height="96" width="10" id="r7" shape-rendering="crispEdges"
                          style="fill: rgb(253, 208, 162); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(123, 101, 79);">
                        <title>Health Care:
                            400</title></rect>
                    <text x="-6" y="48" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Health Care: 400
                    </text>
                </g>
                <g class="node" transform="translate(566,537.6)">
                    <rect height="38.4" width="10" id="r8" shape-rendering="crispEdges"
                          style="fill: rgb(49, 163, 84); fill-opacity: 0.9; stroke-width: 0; stroke: rgb(24, 79, 41);">
                        <title>Other Necessities:
                            160</title></rect>
                    <text x="-6" y="19.2" dy=".35em" text-anchor="end"
                          style="stroke-width: 0; font-family: sans-serif; font-size: 15px; font-weight: 400; fill: rgb(0, 0, 0);">
                        Other Necessities: 160
                    </text>
                </g>
            </g>
        </g>
    </g>
</svg>

diagrams/templates/diagrams/base-sankey.html
{% extends "base/base.html" %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">  -->
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock css %}
{% block js %}

<!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
{% endblock js %}

diagrams/templates/diagrams/diagramassankey.html
{% extends "diagrams/base-sankey.html" %}
{% block title %}Sankey{% endblock title %}
{% block content %}
    {% include "base/nav.html" %}
    {% block diagrama %}
         <style>
            hr {
                display: block;
                margin-top: 0.5em;
                margin-bottom: 0.5em;
                margin-left: auto;
                margin-right: auto;
                border-style: inset;
                border-width: 2px;
            }
        </style>
        <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Resultados
                    <small>Tabla con costos de inversión y ganancias para cada combinación de procesos calculado, para cada año
                        correspondiente y ordenado por su mejor ganancia.
                        Si el costo de inversión es igual a cero, corresponde que todos los materiales fueron incinerados directamente.</small>
                </h1>
            </section>
            <hr>

            <div class="container">
                <h3>Equipo Tratado: {{ equipo }}</h3>

                {% for resultado in resultadoTotal %}
                    <h4>Año: {{ anio|add:forloop.counter0 }}</h4>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th><FONT SIZE=4><b>#</b></font></th>
                            <th><FONT SIZE=4><b>Combinación de Procesos</b></font></th>
                            <th><FONT SIZE=4><b>Inversión</b></font></th>
                            <th><FONT SIZE=4><b>Ganancia</b></font></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for lista in resultado %}
                            <tr>
                                <th scope="row"> {{ lista|first}} </th>
                                <td>
                                    {% for nombre in lista.1 %}
                                        {{ nombre }}
                                        <i class="fa fa-chevron-right"></i>
                                    {% endfor %}
                                </td>
                                <td>
                                   $ {{ lista.2 }}
                                </td>
                            <td>
                                    $ {{ lista.3 }}
                                </td>
                                <td>
                                    <form action="{% url 'diagrams:generateSankey' %}" method="post">{% csrf_token %}

                                        <input type="hidden" value="{{ lista|first }}" name="diagramsID">
                                        <input type="hidden" value="{{ lista|last }}" name="referencia">
                                        <input type="hidden" value="{{ lista.1 }}" name="procesos">
                                        <input type="hidden" value="{{ equipo }}" name="equipo">
                                        <input type="hidden" value="{{ anio }}" name="anio">


                                        <input type="submit" value="Ver Sankey" class="btn btn-warning">
                                    </form>
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}

            </div>


        </div><!-- /.content-wrapper -->

    {% endblock diagrama %}
{% endblock content %}

diagrams/templates/diagrams/sankey.html
{% extends "diagrams/base-sankey.html" %}
{% block title %}Sankey{% endblock title %}
{% block content %}
    {% include "base/nav.html" %}
    {% block diagrama %}

        <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Diagrama SANKEY
                    <small>{{ procesos|safe }}</small>
                </h1>
            </section>

            <script src="/static/diagrams/plotlyjs-bundle.js"></script>

            <!--class="content-wrapper" class="col-lg-3 col-xs-6"-->
            <section class="content">
                <div class="row" >

                    <div id="plotly-div"></div>


                    <script type="text/javascript">

                        Plotly.d3.json('',  function(fig){

                            var data = {
                                type: "sankey",
                                domain: {
                                    x: [0, 1],
                                    y: [0, 1]
                                },
                                orientation: "h",
                                valueformat: " #,###.0f ",
                                valuesuffix: "t",
                                node: {
                                    pad: 15,
                                    thickness: 30,
                                    line: {
                                        color: "black",
                                        width: 0.5
                                    },
                                    label: {{ labelNodo|safe }},
                                    color: {{ colorNodo|safe }},
                                    //width:[10,20,20,50,10,20,20,50,10,20,20,50,10,20,20,50]
                                },
                                link: {
                                    color:{{ colorLink|safe }},
                                            source:{{ source|safe }},
                                            target:{{ target|safe }},
                                            value:{{ values|safe }},
                                            label:{{ labelLink|safe }}
                                }
                            }

                            var data = [data]

                            var layout = {
                                title: "{{ equipo|safe }} {{ anio|safe }}",
                                width: 1118,
                                height: 772,
                                font: {
                                    size: 11
                                },
                                titlefont: {
                                        size:
                                            20,
                                    }
                            }

                            Plotly.plot('plotly-div', data, layout)
                        });
                    </script>


                </div>

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
    {% endblock diagrama %}
{% endblock content %}