SisRAEE/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^diagrams/', include('diagrams.urls')),
    url(r'^processes/', include('processes.urls')),
    #url(r'^chaining/', include('smart_selects.urls')),
]

processes/urls.py
from django.conf.urls import url
#from . import views
from processes.views import newProcess_view, loadEquipoEntrada, getProcesoCalculadoLista_view, getResultadosListView, \
    MaterialCreateView, MaterialListView, MaterialUpdateView, ProcesoCreateView, loadEquipoEntradaFinal, \
    tablaMaterialPrecio

urlpatterns = [
    url(r'^new_Process/$', newProcess_view, name='new_Process'),
    url('ajax/load_EquipoEntrada/', loadEquipoEntrada, name='ajax_load_EquipoEntrada'),
    url('ajax/load_EquipoFinal/', loadEquipoEntradaFinal, name='ajax_load_EquipoFinal'),
    url('ajax/load_TablaPrecio/', tablaMaterialPrecio, name='ajax_load_TablaPrecio'),

    #url('', ProcesoCalculadoListView.as_view(), name='procesoCalculado-list'),
    url(r'^Process_Calculate/$', getProcesoCalculadoLista_view, name='procesoCalculado-list'),
    url(r'^$', getResultadosListView, name='diagramassankey'),
    url('addMaterial/', MaterialCreateView.as_view(), name='material_add'),
    url('listMaterial/', MaterialListView.as_view(), name='material_list'),
    url('<int:pk>/', MaterialUpdateView.as_view(), name='material_update'),
    url('addProceso/', ProcesoCreateView.as_view(), name='proceso_add'),
]

processes/models.py
from django.db import models

from DataBase.DataBaseQuery import getPreciosAnio


class AnioPrecio(models.Model):
    anio=models.IntegerField(db_column='ANIOPRECIO',primary_key=True)
    class Meta:
        managed = True
        db_table = 'ANIOPRECIO'
    def __str__(self):
        return str(self.anio)#+" "+str(getPreciosAnio(self.anio))#str(self.anio)


class Material(models.Model):
    idmaterial = models.AutoField(db_column='IDMATERIAL', primary_key=True)
    nombre = models.CharField(db_column='NOMBRE', max_length=45)

    class Meta:
        managed = True
        db_table = 'MATERIAL'

    def __str__(self):
        return self.nombre

class Equipo(models.Model):
    idequipo = models.AutoField(db_column='IDEQUIPO', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=45)
    materiales = models.ManyToManyField(Material)

    class Meta:
        managed = True
        db_table = 'EQUIPO'
        unique_together = (('nombre'),)

    def __str__(self):
        return self.nombre

class EquipoEntrada(models.Model):
    idequipoentrada = models.AutoField(db_column='IDEQUIPOENTRADA', primary_key=True)  
    idequipo = models.ForeignKey('Equipo', models.DO_NOTHING, db_column='IDEQUIPO')  
    anio = models.IntegerField(db_column='ANIO')  

    class Meta:
        managed = True
        db_table = 'EQUIPOENTRADA'
        unique_together = (('idequipo', 'anio'),)

    def __str__(self):
        return str(self.anio)+" "+str(self.idequipo)

class MasaEntrada(models.Model):
    idmasaentrada = models.AutoField(db_column='IDMASAENTRADA', primary_key=True)
    idequipoentrada = models.ForeignKey('EquipoEntrada', models.DO_NOTHING, db_column='IDEQUIPOENTRADA')  
    idmaterial = models.ForeignKey('Material', models.DO_NOTHING, db_column='IDMATERIAL')  
    masa = models.DecimalField(db_column='MASA', max_digits=50, decimal_places=20)  


    class Meta:
        managed = True
        db_table = 'MASAENTRADA'
        unique_together = (('idequipoentrada', 'idmaterial'),)

class MaterialPrecio(models.Model):
    idmaterialprecio = models.AutoField(db_column='IDMATERIALPRECIO', primary_key=True,verbose_name='Cod')
    anio = models.ForeignKey('AnioPrecio', models.DO_NOTHING, db_column='ANIOPRECIO',verbose_name='Año')
    idmaterial = models.ForeignKey('Material', models.DO_NOTHING, db_column='IDMATERIAL',verbose_name='Material')
    precioreventa = models.DecimalField(db_column='PRECIOREVENTA', max_digits=50, decimal_places=2,verbose_name='Precio Venta $')

    class Meta:
        managed = True
        db_table = 'MATERIALPRECIO'
        unique_together = (('anio', 'idmaterial'),)

    def __str__(self):
        return str(self.idmaterial) + " €" + str(float(self.precioreventa))

class Grupo(models.Model):
    idgrupo = models.AutoField(db_column='IDGRUPO', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=45)  

    class Meta:
        managed = True
        db_table = 'GRUPO'

    def __str__(self):
        return self.nombre

class Tipo(models.Model):
    idtipo = models.AutoField(db_column='IDTIPO', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=45)  

    class Meta:
        managed = True
        db_table = 'TIPO'

    def __str__(self):
        return self.nombre

class Densidad(models.Model):
    iddensidad = models.AutoField(db_column='IDDENSIDAD', primary_key=True)  
    densidad = models.DecimalField(db_column='DENSIDAD', max_digits=50, decimal_places=20)  

    class Meta:
        managed = True
        db_table = 'DENSIDAD'
        unique_together = (('iddensidad', 'densidad'),)

    def __str__(self):
        return str(self.iddensidad)

class DensidadMaterial(models.Model):
    iddensidad = models.ForeignKey('Densidad', models.DO_NOTHING,db_column='IDDENSIDAD')  
    idmaterial = models.ForeignKey('Material', models.DO_NOTHING, db_column='MATERIAL_IDMATERIAL')  
    valor = models.DecimalField(db_column='VALOR', max_digits=50, decimal_places=20)  

    class Meta:

        db_table = 'DENSIDADMATERIAL'
        unique_together = (('iddensidad', 'idmaterial'),)

class Proceso(models.Model):
    idproceso = models.AutoField(db_column='IDPROCESO', primary_key=True)  
    proceso = models.CharField(db_column='PROCESO', max_length=45,verbose_name='Nombre Proceso')
    idgrupo = models.ForeignKey('Grupo', models.DO_NOTHING, db_column='GRUPO',verbose_name='Grupo')
    idtipo = models.ForeignKey('Tipo', models.DO_NOTHING, db_column='TIPO',verbose_name='Tipo')
    materiales = models.ManyToManyField(Material)#db_table='Material_has_Proceso'  through='Material_has_Proceso'
    costotratamiento = models.DecimalField(db_column='COSTOTRATAMIENTO', max_digits=50,decimal_places=20,verbose_name='Costotra Tamiento')
    costoinversion = models.DecimalField(db_column='COSTOINVERSION', max_digits=50, decimal_places=20,verbose_name='Costo Inversion')
    rendimientominimo = models.DecimalField(db_column='RENDIMIENTOMINIMO', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Rendimiento Minimo')
    incrementorendimiento=models.DecimalField(db_column='INCREMENTORENDIMIENTO', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Incremento Rendimiento')
    tiempodepreciacion=models.DecimalField(db_column='TIEMPODEPRECIACION', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Tiempo Depreciacion')
    iddensidad=models.ForeignKey('Densidad', models.DO_NOTHING, db_column='IDDENSIDAD', blank=True, null=True,verbose_name='Densidad')
    loop=models.CharField(db_column='LOOP', max_length=45,verbose_name='Loop')
    procesoid=models.IntegerField(db_column='PROCESOID', null=True,verbose_name='Proceso Id')
    mantenimientotonelada=models.DecimalField(db_column='MANTENIMIENTOTONELADA', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Mantenimiento Tonelada $')
    manoobratonelada=models.DecimalField(db_column='MANOOBRATONELADA', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Mano Obra Tonelada $')
    energia=models.DecimalField(db_column='ENERGIA', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Energia')
    otros = models.DecimalField(db_column='OTROS', max_digits=50, decimal_places=20, blank=True, null=True,verbose_name='Otros')

    class Meta:
        managed = True
        db_table = 'PROCESO'
        unique_together = (('idproceso','idgrupo','idtipo'),)

    def __str__(self):
        return self.proceso

class RendimientoProceso(models.Model):
    idmaterial = models.ForeignKey(Material, models.DO_NOTHING,related_name='materialidmaterial', db_column='IDMATERIAL')  
    idmaterialreferencia = models.ForeignKey(Material, models.DO_NOTHING, related_name='idmaterialRefe', db_column='IDMATERIALREFERENCIA')
    #idmaterialreferencia = models.IntegerField(db_column='IDMATERIALREFERENCIA')
    idproceso = models.ForeignKey(Proceso, models.DO_NOTHING, db_column='IDPROCESO')  
    valor = models.DecimalField(db_column='VALOR', max_digits=50, decimal_places=20)  

    class Meta:
        managed = True
        db_table = 'RENDIMIENTOPROCESO'
        unique_together = (('idmaterial', 'idmaterialreferencia', 'idproceso'),)

class ProcesoCalculado(models.Model):
    idprocesocalculado = models.AutoField(db_column='IDPROCESOSCALCULADO', primary_key=True)
    idprocesos=models.ManyToManyField(Proceso)
    idanioprecio=models.ForeignKey(AnioPrecio,models.DO_NOTHING,db_column='ANIOPRECIO')
    idequipoentradainicio=models.ForeignKey(EquipoEntrada,models.DO_NOTHING,db_column='IDENTRADAINICIO',related_name='ANIOINICIO')
    idequipoentradafinal=models.ForeignKey(EquipoEntrada,models.DO_NOTHING,db_column='IDENTRADAFINAL',related_name='ANIOFINAL')
    idequipo=models.ForeignKey(Equipo,models.DO_NOTHING,db_column='IDEQUIPO')
    class Meta:
        managed = True
        db_table = 'PROCESOCALCULADO'

    def __str__(self):
        return str(self.idequipo)+" "+str(self.idequipoentradainicio)+" "+str(self.idequipoentradafinal)


class ProcesoSeparacionId(models.Model):
    idprocesosseparacionid = models.AutoField(db_column='IDPROCESOSSEPARACIONID', primary_key=True)  
    anio = models.IntegerField(db_column='ANIO')  
    idprocesocalculado=models.ForeignKey(ProcesoCalculado,models.DO_NOTHING,db_column='IDPROCESOCALCULADO')
    #idequipo=models.ForeignKey(Equipo, models.DO_NOTHING, db_column='IDEQUIPO')
    class Meta:
        managed = True
        db_table = 'PROCESOSEPARACIONID'
        unique_together = (('idprocesosseparacionid', 'anio'),)

class ProcesoSeparacion(models.Model):
    idprocesosseparacion = models.AutoField(db_column='IDPROCESOSSEPARACION',primary_key=True)  
    idprocesosseparacionid = models.ForeignKey(ProcesoSeparacionId, models.DO_NOTHING, db_column='IDPROCESOSSEPARACIONID')  
    secuenciaprocesoseparacion = models.IntegerField(db_column='SECUENCIAPROCESOSEPARACION')  
    inversion=models.DecimalField(db_column='INVERSION', max_digits=50, decimal_places=20)  
    valorneto=models.DecimalField(db_column='VALORNETO', max_digits=50, decimal_places=20)  

    class Meta:
        managed = True
        db_table = 'PROCESOSEPARACION'
        unique_together = (('idprocesosseparacionid', 'secuenciaprocesoseparacion'),)

class ProcesoCombinacion(models.Model):
    idprocesocombinacion = models.AutoField(db_column='IDPROCESOCOMBINACION',primary_key=True)
    idprocesosseparacion = models.ForeignKey('ProcesoSeparacion', models.DO_NOTHING, related_name='PSidprocesosseparacion', db_column='IDPROCESOSSEPARACION')
    secuencia = models.IntegerField(db_column='SECUENCIA')
    idprocesosalida = models.ForeignKey('Proceso', models.DO_NOTHING, db_column='IDPROCESOSALIDA', null=True)
    idprocesoprevio = models.ForeignKey('Proceso', models.DO_NOTHING, db_column='IDPROCESOPREVIO',related_name='idprocesoPre', null=True)
        #models.IntegerField(db_column='IDPROCESOPREVIO', blank=True, null=True)

processes/forms.py
from django import forms
from django.forms import CheckboxInput, CheckboxSelectMultiple, BooleanField

from processes.models import ProcesoCalculado, Equipo, EquipoEntrada, Material, Proceso
from django.core.exceptions import ValidationError


class startProcessForm(forms.ModelForm):
    class Meta:
        model = ProcesoCalculado

        fields = [
            'idprocesos',
            'idanioprecio',
            'idequipoentradainicio',
            'idequipoentradafinal',
            'idequipo'
        ]

    def __init__(self, *args, **kwargs):

        super(startProcessForm, self).__init__(*args, **kwargs)

        self.fields["idprocesos"].widget = CheckboxSelectMultiple()
        self.fields["idprocesos"].queryset = Proceso.objects.all()

    def clean(self):
        equipo = self.cleaned_data.get('idequipo').idequipo
        final = self.cleaned_data.get('idequipoentradafinal')
        inicial = self.cleaned_data.get('idequipoentradainicio')
        if equipo == None or final == None or inicial == None:
            raise ValidationError(" Datos requeridos no ingresados.")
        anioinicial = inicial.anio
        aniofinal = final.anio
        equipoinicial = inicial.idequipo.idequipo
        equipofinal = final.idequipo.idequipo
        if (equipofinal != equipoinicial or equipo != equipoinicial or equipo != equipoinicial):
            raise ValidationError(" El Equipo del Año Inicial y Año Final den ser igual del AEE.")
        if (anioinicial > aniofinal):
            raise ValidationError("Año Final debe ser mayor o igual al Año Inicial.")

        return self.cleaned_data


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['nombre']


class ProcesoForm(forms.ModelForm):
    materiales = BooleanField(
        widget=CheckboxSelectMultiple(
            attrs={'data-validation-error-msg': 'You have to agree to our terms and conditions'}))
    class Meta:
        model = Proceso
        fields = ['proceso',
                  'idgrupo',
                  'idtipo',
                  'materiales',
                  'costotratamiento',
                  'costoinversion',
                  'rendimientominimo',
                  'incrementorendimiento',
                  'tiempodepreciacion',
                  'iddensidad',
                  'loop',
                  'procesoid',
                  'mantenimientotonelada',
                  'manoobratonelada',
                  'energia',
                  'otros']

    def __init__(self, *args, **kwargs):
        super(ProcesoForm,self).__init__(*args, **kwargs)
        #self.fields['materiales'].widget = forms.CheckboxSelectMultiple()
        #self.fields['materiales'].widget = CheckboxInput()
        self.fields['materiales'].widget =forms.MultipleChoiceField(

            widget=forms.CheckboxSelectMultiple

        )

processes/templates/processes/base-processes.html
{% extends "base/base.html" %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">  -->
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- calendario -->
     <link href="/static/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
    <!--endcalendario-->
{% endblock css %}
{% block js %}

    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
{% endblock js %}

processes/templates/processes/material_form.html
{% extends "processes/base-processes.html" %}
{% block title %}Proceso{% endblock title %}
{% block content %}
    {% block processes %}script
        {% include "base/nav.html" %}
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    Material
                    <small>Nuevo</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active"><i class="fa fa-dashboard"></i> Inicio</li>
                </ol>
            </section>
            <form method="post" id="materialForm" class="form-horizontal"a>
                {% csrf_token %}
                <div class="form-group">
                    <h3>
                        <small><label class="col-xs-3 control-label">Nombre: </label></small>
                    </h3>
                    {% csrf_token %}
                    <div class="col-xs-2 selectContainer">
                        {% csrf_token %}
                        {{ form.nombre }}
                    </div>


                </div>
                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>


    {% endblock %}
{% endblock %}

processes/templates/processes/material_list.html
{% extends "processes/base-processes.html" %}
{% block title %}Proceso{% endblock title %}
{% block content %}
    {% block processes %}script
        {% include "base/nav.html" %}
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    Materiales

                </h1>
                <ol class="breadcrumb">
                    <li class="active"><i class="fa fa-dashboard"></i> Inicio</li>
                </ol>
            </section>


            <div class="container">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th><FONT SIZE=4><b>Cod</b></font></th>
                        <th><FONT SIZE=4><b>Nombre Material</b></font></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </br></br>
                    <tr>
                        <form action="{% url 'material_add' %}" method="post">{% csrf_token %}

                            <input type="submit" value="Nuevo Material" class="btn btn-primary">
                        </form>
                    </tr>
                    {% for material in materiales %}

                        <tr>
                            <td> {{ material.idmaterial }} </td>
                            <td> {{ material.nombre }} </td>

                            <td>
                                {% comment %}<a href="{% url 'material_update' 0 %}">Modificar</a>{% endcomment %}
                                <form action="{% url 'material_update' %}" method="post">{% csrf_token %}

                                    <input type="hidden" value="{{ material.idmaterial }}" name="pk">

                                    <input type="submit" value="Modificar" class="btn btn-warning">
                                </form>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    {% endblock %}
{% endblock %}

processes/templates/processes/proceso_form.html
{% extends "processes/base-processes.html" %}
{% block title %}Proceso{% endblock title %}
{% block content %}
    {% block processes %}script
        {% include "base/nav.html" %}
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    Proceso
                    <small>Nuevo</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active"><i class="fa fa-dashboard"></i> Inicio</li>
                </ol>
            </section>
            <form method="post" id="procesoForm" class="form-horizontal" a>
                {% csrf_token %}
                {% for val in form %}
                    <div class="form-group">
                        <h3>
                            <small><label class="col-xs-3 control-label">{{ val.label }} </label></small>
                        </h3>
                        {% csrf_token %}
                        <div class="col-xs-2 selectContainer">
                            {% csrf_token %}
                            {{ val }}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>


    {% endblock %}
{% endblock %}

processes/templates/processes/selectOptionEquipoEntrada.html
<option value="">---------</option>
{% for idequipoentrada in equipoEnt %}
<option value="{{ idequipoentrada.idequipoentrada }}">{{ idequipoentrada }}</option>
{% endfor %}

processes/templates/processes/selectOptionEquipoFinal.html
<option value="">---------</option>
{% for idequipoentrada in equipoEnt %}
<option value="{{ idequipoentrada.idequipoentrada }}">{{ idequipoentrada }}</option>
{% endfor %}

processes/templates/processes/startprocess.html
{% extends "processes/base-processes.html" %}
{% block title %}Proceso{% endblock title %}
{% block content %}
    {% block processes %}script
        {% include "base/nav.html" %}
        <style>
            hr {
                display: block;
                margin-top: 0.5em;
                margin-bottom: 0.5em;
                margin-left: auto;
                margin-right: auto;
                border-style: inset;
                border-width: 2px;
            }
        </style>
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    Cálculo
                    <small>PROCESOS</small>
                </h1>
            </section>
            <hr>
            <form id="processesForm" method="post" class="form-horizontal"
                  data-equipo-ent-url="{% url 'ajax_load_EquipoEntrada' %}"
                  data-equipo-sal-url="{% url 'ajax_load_EquipoFinal' %}"
                  data-anioprecio-tbl-url="{% url 'ajax_load_TablaPrecio' %}">
                <div class="form-group">

                    <h3>
                        <small><label class="col-xs-3 control-label">Procesos: </label></small>
                    </h3>

                    {% csrf_token %}

                    <div class="col-xs-4 checkbox" checked>
                        <input id="id_todos" name="something" type="checkbox">
                        <b>Seleccionar Todos</b>
                        {% csrf_token %}
                        <FONT SIZE=2>{{ form.idprocesos }}</FONT>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <h3>
                            <small><label class="col-xs-3 control-label">Aparato eléctrico o eléctronico (AEE): </label></small>
                        </h3>
                        <div class="col-xs-2 selectContainer">
                            {% csrf_token %}
                            {{ form.idequipo }}
                        </div>
                        <div class="col-md-5"></div>
                    </div>

                </div>

                <div class="form-group">

                    <div class="row">

                        <h3>
                            <small><label class="col-xs-3 control-label">Año Precio Reventa: </label></small>
                        </h3>

                        <div class="col-xs-2 selectContainer">
                            {% csrf_token %}
                            {{ form.idanioprecio }}
                        </div>

                        <div id="id_tabla"  class="col-md-5">
                            {% load django_tables2 %}
                            {% render_table table %}
                        </div>
                    </div>


                </div>
                <div class="form-group">
                    <div class="row">
                        <h3>
                            <small><label class="col-xs-3 control-label">Año Inicial: </label></small>
                        </h3>
                        <div class="col-xs-2 selectContainer">
                            {% csrf_token %}
                            {{ form.idequipoentradainicio }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <h3>
                            <small><label class="col-xs-3 control-label">Año Final: </label></small>
                        </h3>
                        <div class="col-xs-2 selectContainer">
                            {% csrf_token %}
                            {{ form.idequipoentradafinal }}
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <input type="submit" value="Iniciar Proceso" class="btn btn-warning">
                    </div>
                </div>

                {% if form.errors %}
                    <div class="alert alert-error">
                        <!--<h4>Error</h4>-->
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a><br>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                        {% if form.non_field_errors %}
                            {{ form.non_field_errors }}
                        {% endif %}
                    </div>
                {% endif %}

            </form>

        </div>


        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script type="text/javascript">
            $("#id_idequipo").change(function () {
                var url = $("#processesForm").attr("data-equipo-ent-url");
                var equipoId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'idequipo': equipoId
                    },
                    success: function (data) {
                        $("#id_idequipoentradainicio").html(data);

                    }
                });
            });

            $("#id_idequipoentradainicio").change(function () {
                var url = $("#processesForm").attr("data-equipo-sal-url");
                var idequipoentrada = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'idequipoentrada': idequipoentrada
                    },
                    success: function (data) {
                        $("#id_idequipoentradafinal").html(data);
                    }
                });
            });

            $("#id_idanioprecio").change(function () {
                var url = $("#processesForm").attr("data-anioprecio-tbl-url");
                var anio = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'anio': anio
                    },
                    success: function (data) {
                        $("#id_tabla").html(data);
                    }
                });
            });

            $("#id_idprocesos").change(function () {

                var checkBox = document.getElementById("id_todos");
                if (checkBox.checked) {
                    checkBox.checked = false;
                }

            });

            $("#id_todos").change(function () {
                if (this.checked) {
                    var checkP = document.getElementById("id_idprocesos")
                    for (var i = 0; i < checkP.childElementCount; i++) {
                        $("#id_idprocesos_" + i).prop("checked", true);
                    }


                }
            });
        </script>
    {% endblock %}
{% endblock %}

processes/templates/processes/table_materialprecio.html
{% load django_tables2 %}
{% render_table table %}